/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostelmanagement;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.IOException;

/**
 *
 * @author Atel Dot Net
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        BanglaFont();
    }
  public void BanglaFont() {
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, getClass().getResource("k.TTF").openStream());

            GraphicsEnvironment genv = GraphicsEnvironment.getLocalGraphicsEnvironment();
            genv.registerFont(font);
// makesure to derive the size
            font = font.deriveFont(28f);
            jLabel2.setFont(font);
            jLabel2.setText("লতিফ ছাত্রাবাস ");
           // jTextField1.setFont(font);
            
        } catch (IOException e) {
            e.printStackTrace();
        } catch (FontFormatException e) {
            e.printStackTrace();
        }
       

//use the font
//yourSwingComponent.setFont(customFont);
        //Handle exception
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PayementPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AdmissionPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InfoPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IdentityPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("লতিফ ছাত্রাবাস ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(410, 10, 360, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(120, 80, 1070, 80);

        PayementPanel.setBackground(new java.awt.Color(51, 153, 255));
        PayementPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PayementPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PayementPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PayementPanelMouseExited(evt);
            }
        });
        PayementPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAYEMENT");
        PayementPanel.add(jLabel1);
        jLabel1.setBounds(70, 0, 120, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/payement.png"))); // NOI18N
        PayementPanel.add(jLabel3);
        jLabel3.setBounds(90, 50, 80, 80);

        jPanel1.add(PayementPanel);
        PayementPanel.setBounds(280, 440, 280, 150);

        AdmissionPanel.setBackground(new java.awt.Color(51, 153, 255));
        AdmissionPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AdmissionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdmissionPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdmissionPanelMouseExited(evt);
            }
        });
        AdmissionPanel.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADMISSION FORM");
        AdmissionPanel.add(jLabel4);
        jLabel4.setBounds(60, 0, 200, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/newMember.png"))); // NOI18N
        AdmissionPanel.add(jLabel5);
        jLabel5.setBounds(100, 50, 70, 80);

        jPanel1.add(AdmissionPanel);
        AdmissionPanel.setBounds(280, 230, 280, 150);

        InfoPanel.setBackground(new java.awt.Color(51, 153, 255));
        InfoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        InfoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InfoPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InfoPanelMouseExited(evt);
            }
        });
        InfoPanel.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STUDENT INFO");
        InfoPanel.add(jLabel6);
        jLabel6.setBounds(70, 0, 140, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/info.png"))); // NOI18N
        InfoPanel.add(jLabel7);
        jLabel7.setBounds(90, 50, 80, 80);

        jPanel1.add(InfoPanel);
        InfoPanel.setBounds(640, 230, 280, 150);

        IdentityPanel.setBackground(new java.awt.Color(51, 153, 255));
        IdentityPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IdentityPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IdentityPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IdentityPanelMouseExited(evt);
            }
        });
        IdentityPanel.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("IDENTITY");
        IdentityPanel.add(jLabel8);
        jLabel8.setBounds(90, 0, 110, 70);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/identity.png"))); // NOI18N
        IdentityPanel.add(jLabel9);
        jLabel9.setBounds(110, 50, 80, 80);

        jPanel1.add(IdentityPanel);
        IdentityPanel.setBounds(640, 440, 280, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1320, 690);

        setSize(new java.awt.Dimension(1336, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PayementPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayementPanelMouseEntered
        // TODO add your handling code here:
        PayementPanel.setBackground(new java.awt.Color(255, 0, 51));
    }//GEN-LAST:event_PayementPanelMouseEntered

    private void PayementPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayementPanelMouseExited
        // TODO add your handling code here:
         PayementPanel.setBackground(new java.awt.Color(51,153,255));
    }//GEN-LAST:event_PayementPanelMouseExited

    private void AdmissionPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmissionPanelMouseEntered
        // TODO add your handling code here:
        AdmissionPanel.setBackground(new java.awt.Color(255, 0, 51));
    }//GEN-LAST:event_AdmissionPanelMouseEntered

    private void AdmissionPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmissionPanelMouseExited
        // TODO add your handling code here:
         AdmissionPanel.setBackground(new java.awt.Color(51,153,255));
    }//GEN-LAST:event_AdmissionPanelMouseExited

    private void InfoPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoPanelMouseEntered
        // TODO add your handling code here:
              InfoPanel.setBackground(new java.awt.Color(255, 0, 51));

    }//GEN-LAST:event_InfoPanelMouseEntered

    private void InfoPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoPanelMouseExited
        // TODO add your handling code here:
         InfoPanel.setBackground(new java.awt.Color(51,153,255));
    }//GEN-LAST:event_InfoPanelMouseExited

    private void IdentityPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdentityPanelMouseEntered
        // TODO add your handling code here:
         IdentityPanel.setBackground(new java.awt.Color(255, 0, 51));
    }//GEN-LAST:event_IdentityPanelMouseEntered

    private void IdentityPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdentityPanelMouseExited
        // TODO add your handling code here:
        IdentityPanel.setBackground(new java.awt.Color(51,153,255));
    }//GEN-LAST:event_IdentityPanelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdmissionPanel;
    private javax.swing.JPanel IdentityPanel;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JPanel PayementPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
