/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostelmanagement;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Atel Dot Net
 */
public class IdCard extends javax.swing.JFrame {

    /**
     * Creates new form IdCard
     */
    public IdCard() {
        initComponents();
        BanglaFont();
    }
  public void BanglaFont() {
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, getClass().getResource("k.ttf").openStream());

            GraphicsEnvironment genv = GraphicsEnvironment.getLocalGraphicsEnvironment();
            genv.registerFont(font);
// makesure to derive the size
            font = font.deriveFont(18f);
            
            jPanel1.setFont(font);
            jLabel1.setFont(font);
            jLabel2.setFont(font);
              jLabel1.setFont(font);
            jLabel3.setFont(font);
              jLabel4.setFont(font);
            jLabel5.setFont(font);
              jLabel6.setFont(font);
            jLabel7.setFont(font);
             // jLabel8.setFont(font);
            jLabel9.setFont(font);
             // jLabel10.setFont(font);
            //jLabel11.setFont(font);
             // jLabel12.setFont(font);
            //jLabel13.setFont(font);
              jLabel14.setFont(font);
              jLabel15.setFont(font);
              
               jLabel8.setFont(font);
              jLabel10.setFont(font);
              
             
              
           // jTextPane1.setFont(font);
          //  MemberName.setFont(font);
            
           // jTextField1.setFont(font);
            
        } catch (IOException e) {
            e.printStackTrace();
        } catch (FontFormatException e) {
            e.printStackTrace();
        }
       
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("লতিফ ছাত্রাবাস (পূর্ব শাখা )");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 30, 200, 20);

        jLabel2.setText("তত্তাবদায়েকের কার্যালয় ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 50, 140, 20);

        jLabel3.setText("ঢাকা পলিটেকনিক ইনস্টিটিউট");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 70, 180, 20);

        jLabel4.setText("তেজগাঁও ঢাকা -1208 ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 90, 130, 30);

        jLabel5.setText("পরিচয়পত্র");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 130, 90, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/Images/logoIcon.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 30, 100, 100);

        jLabel7.setText("            ছবি ");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(410, 30, 110, 120);

        jLabel9.setText("আইডি নং : 12345678");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 180, 510, 30);

        jLabel14.setText(" সুপার ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(400, 400, 110, 20);

        jLabel15.setText("সহকারী সুপার ");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 400, 110, 20);

        jLabel8.setText("                      লতিফ পূর্ব শাখার একজন নিয়মিত ছাত্র  তাহার ক্রমিক নং : শিক্ষাবর্ষ : কক্ষ নং :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 280, 500, 30);

        jLabel10.setText("                      প্রত্যয়ন করা যাচ্ছে যে - তানভীর হাসান   অত্র প্রতিষ্টানের বিজ্ঞান বিভাগের ছাত্র ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 240, 500, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(350, 120, 550, 430);

        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 590, 110, 60);

        setSize(new java.awt.Dimension(1343, 758));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try
        {
            Toolkit tkp = jPanel1.getToolkit();
            PrintJob pjp = tkp.getPrintJob(this, null, null);
            Graphics g = pjp.getGraphics();
            jPanel1.print(g);
            g.dispose();
            pjp.end();
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
